Yform Value hinzugefügt
FriendsOfREDAXO/cropper pull request #52
Opened 2024-10-29 15:49 UTC by skerbis

Croppen nun auch mit YFORM. As simple as possible

2024-10-29 16:02 UTC, skerbis commented
<img width="1345" alt="Bildschirmfoto 2024-10-29 um 16 58 21" src="https://github.com/user-attachments/assets/106109ff-9258-4643-8059-57d6b612a7d2">
<img width="634" alt="Bildschirmfoto 2024-10-29 um 17 01 48" src="https://github.com/user-attachments/assets/55fe3f95-bd40-4f9c-8d34-3290345a8392">

2024-10-29 23:20 UTC, alxndr-w requested changes
M.E.

- [ ] Feld sollte be_media_crop heißen, da es nur fürs Backend ist
- [ ] Media-Kategorie-Select statt id
- [ ] crop/preview width und height als ganzzahliges positives Integer-Felder
- [ ] Zeile 104: Warnung nicht übersetzt
- [ ] Zeille 28: $_POST verwendet anstelle von rex_post()
- [ ] Umsetzung erfordert yform-Page, sollte aber auch auf Addon-Pages funktionieren (neues, events, ...)

2024-10-30 00:12 UTC, skerbis commented
> Feld sollte be_media_crop heißen, da es nur fürs Backend ist
Nein , es kann auch im FE verwendet werden 
>  Umsetzung erfordert yform-Page, sollte aber auch auf Addon-Pages funktionieren (neues, events, ...)
mal schauen , können auch einen anderen page Part nehmen

2024-10-30 00:45 UTC, skerbis commented
> Media-Kategorie-Select statt id
Keine Ahnung wie man das hier reinfummelt

2024-10-30 09:37 UTC, skerbis commented
@alxndr-w 
Um nicht unnötig bei jedem AddOn das YForm verwendet die Assets zu laden, müssten wir uns was einfallen lassen. 
Aktuell würde ich es so belassen. 
Man kann die Assets ja auch aus dem jeweiligen AddOn heraus laden. Vielleicht könnten wir eine Methode dafür bauen.

2024-10-30 09:41 UTC, skerbis commented
> Für die Media Category, pack choice rein mit SQL auf rex_media_category
Gerne übernehmen

Preview?

2024-10-30 13:21 UTC, alxndr-w commented
Preview?

2024-10-30 15:41 UTC, skerbis commented
du hast nach preview gefragt 😜

2024-10-30 16:21 UTC, alxndr-w commented
Ja und immer noch keine Antwort.

> Was ist die Aufgabe des Parameters "Preview"?

Deutlicher: Was macht preview_width und preview_height? Wo? Wie ist das gedacht? Ich verstehe nichts darunter, außer irgendwas mit Vorschau? Kann man 2 Bildausschnitte wählen, ein zugeschnittenes und eins für eine Vorschau?

2024-10-30 16:37 UTC, skerbis commented
Es gibt ne Bühne 
und es gibt das Crop

<img width="392" alt="Bildschirmfoto 2024-10-30 um 17 36 19" src="https://github.com/user-attachments/assets/3f77e3c1-44db-4054-9c84-fd358ce99ae2">

2024-11-01 12:14 UTC, alxndr-w commented
Ich raff es nicht. Ich würde nicht gern wissen, was es gibt, sondern wozu.

2024-11-02 16:21 UTC, skerbis commented
Wozu? Um es so zu gestalten wie man es haben will 

<img width="1591" alt="Bildschirmfoto 2024-11-02 um 17 17 07" src="https://github.com/user-attachments/assets/b5f92c1a-9dd2-40ab-a0be-2e42c379911b">

2024-11-06 09:08 UTC, merged